# @package _global_
defaults:
  - wandb: defaults
  - train: defaults
  - dataset: defaults
  - _self_

train:
  epochs: 40
  milestones: [30,38]

prune_amount: 0.7

hydra:
  run:
    dir: ../output/pnml_prune_${prune_amount}_${now:%Y%m%d_%H%M%S}
